import InitialTheme from '@/components/modules/InitialTheme'
import type { Metadata, Viewport } from 'next'
import localFont from 'next/font/local'
import { Toaster } from 'react-hot-toast'
import './globals.css'
import ReactQueryProvider from '@/providers/ReactQueryProvider'

const dana = localFont({
  src: [
    {
      path: '../assets/fonts/dana/DanaFaNum-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/dana/DanaFaNum-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/dana/DanaFaNum-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--ffont-dana',
  display: 'swap',
})

const morabba = localFont({
  src: [
    {
      path: '../assets/fonts/morabba/Morabba-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../assets/fonts/morabba/Morabba-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/morabba/Morabba-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--ffont-morabba',
  display: 'swap',
})
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Todo X',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  themeColor: '#7480ff',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fa" dir="rtl" className={`${dana.variable} ${morabba.variable} overflow-x-hidden`}>
      <body className={dana.className}>
        <ReactQueryProvider>
          {children}
          <Toaster />
          <InitialTheme />
        </ReactQueryProvider>
      </body>
    </html>
  )
}
